// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, task, status, created_at, updated_at, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, task, status, created_at, updated_at, user_id
`

type CreateTaskParams struct {
	ID        uuid.UUID
	Task      string
	Status    bool
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.Task,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :one
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
RETURNING id, task, status, created_at, updated_at, user_id
`

type DeleteTaskParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, deleteTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT id, task, status, created_at, updated_at, user_id FROM tasks WHERE user_id = $1
`

func (q *Queries) GetAllTasks(ctx context.Context, userID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, task, status, created_at, updated_at, user_id FROM tasks
WHERE id = $1 AND user_id = $2
`

type GetTaskByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const toggleTask = `-- name: ToggleTask :one
UPDATE tasks
SET
    status = $1,
    updated_at = $2
    WHERE id = $3 AND user_id = $4
RETURNING id, task, status, created_at, updated_at, user_id
`

type ToggleTaskParams struct {
	Status    bool
	UpdatedAt time.Time
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) ToggleTask(ctx context.Context, arg ToggleTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, toggleTask,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    task = $1,
    updated_at = $2
    WHERE id = $3 AND user_id = $4
RETURNING id, task, status, created_at, updated_at, user_id
`

type UpdateTaskParams struct {
	Task      string
	UpdatedAt time.Time
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Task,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
